# Generated by Django 5.0 on 2023-12-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numReferencia', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('poblacion', models.CharField(max_length=80)),
                ('cp', models.CharField(max_length=10)),
                ('precio', models.FloatField()),
                ('metroscuadrados', models.IntegerField()),
                ('numHabitaciones', models.IntegerField()),
                ('planta', models.IntegerField()),
                ('banios', models.IntegerField()),
                ('ascensor', models.BooleanField()),
                ('garaje', models.BooleanField()),
                ('terraza', models.BooleanField()),
                ('descCorta', models.CharField(max_length=200)),
                ('comentario', models.TextField()),
                ('correoContacto', models.EmailField(max_length=254)),
                ('fechaAlta', models.DateField(auto_now_add=True)),
                ('fechaModificacion', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['poblacion', 'cp'],
            },
        ),
    ]
