# Generated by Django 5.0 on 2023-12-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piso',
            name='cp',
            field=models.CharField(max_length=20),
        ),
    ]
