# Generated by Django 5.0 on 2023-12-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_cliente_inversor'),
    ]

    operations = [
        migrations.AddField(
            model_name='piso',
            name='imagenPiso',
            field=models.ImageField(blank=True, null=True, upload_to='imgPisos', verbose_name='Imagen de piso'),
        ),
    ]
